version: '3'

services:

  ionic-myappname:
    container_name: myappname-frontend
    build: .
    ports:
      - 8100:8100
      - 35729:35729
    volumes:
      - ./app:/usr/app
      # - /usr/app/node_modules # to not share node_modules
    command: ionic serve --external




