version: '3'

services:

  ionic-myappname:
    container_name: myappname-frontend
    build: .
    ports:
      - 8100:8100
      - 35729:35729
    volumes:
      - ./app:/usr/app

    command: ash -c "npm install -y && ionic serve --external" # For DEV 




